[package]
name = "e4symkey"
version = "0.1.0"
authors = ["Teserakt <team@teserakt.io>"]
build = "build.rs"

[build-dependencies]
bindgen = "0.52.0"

[lib]
name = "e4symkey"
crate-type = ["staticlib"]
